# Generated by Django 4.0.4 on 2022-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_expense_profile_delete_images_delete_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
