# Generated by Django 4.0.4 on 2022-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_expense_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expense',
            field=models.FloatField(default=0),
        ),
    ]
